### ISSUE TITLE
Add how to validate NDA submissions

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/dcan-labs-informational-guide#124]
From the NDA:
```
You can view under the Data Expected tab which data structures have been uploaded if the Subjects Submitted column for the structure is greater than zero. 
 
If you need more information than that, you can download your previous submissions and review the data that way. 
 
To download previous submissions:
You must have 'Admin' permissions on your NDA Collection.
Visit your NDA Collection and click the 'Submissions' tab.
Select the submission(s) you’d like to review and download, then click "Add to Filter Cart" in the bottom left corner.
Wait for your Filter Cart to finish updating, then click “Create Data Package/Add Data to Study”.
Create your data package.
Download your submission using the [NDA Download Manager](https://nda.nih.gov/nda/nda-tools.html#download-manager) or the python tool.
```

`No, there is no programmatic way to do this. If you follow Lorraine's instructions above you can create a single fmriresults01.txt file containing all of the subjects in your submissions. You not need to download the imaging files - a package containing thousands of subjects would only be MB or GB large if you do not include the imaging files. The option to include imaging files in your package is presented on the same page where you name your package. By default it is not selected, so if you create a package and leave all the default settings, you should be able to get the information you are looking for.`

**Comment by rosemccollum** [comment]
Added instructions and reference to upload readthedocs documentation
