### ISSUE TITLE
Add note that scontrol can be used to change from agate/mesabi to a federated partition after job is submitted

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/dcan-labs-informational-guide#180]
Not sure where it's best to add off the top of my head, but it would be good to include this detail:

scontrol cannot be used to change from agate to mesabi or vice versa once a job has been submitted, but it can be used to change from agate or mesabi partitions to federated partitions

https://www.msi.umn.edu/partitions

**Comment by begim-f** [comment]
The note has been added
