### ISSUE TITLE
Add how to download data from the NDA without nda-abcd-s3-downloader

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/dcan-labs-informational-guide#181]

**Comment by rosemccollum** [comment]
@audreymhoughton Luci already opened an issue (#132 ) about adding a how to download data from the NDA so I'm going to close this issue

**Comment by audreymhoughton** [comment]
@rosemccollum - this is actually referencing how to download the data WITHOUT the s3 downloader, so as long as we intend on adding both options via that issue - that's fine!
