### ISSUE TITLE
Migrate DCAN Labs readthedocs content

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/dcan-labs-informational-guide#60]
- migrate information missing from the DPH that's in the DCAN readthedocs into the DPH (https://dcanlab.readthedocs.io/en/stable/) 
- some information may be outdated, so we will have to review each addition one by one (I would make each section a basecamp step and then ask for a review as each section is finished)
- archive DCAN readthedocs repository
- rename the data processing handbook to DCAN Labs' readthedocs
- rename the data processing handbook repository as well

**Comment by rosemccollum** [comment]
Add Lab About us, account, delay and problems, reporting errors, CMRR transfer, Tier1 <-> local storage, Box (not good for large amounts of data), coding workflow, versioning (will work through the rest of it later)
